services:
  - type: web
    name: ocr-backend
    env: python
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
